# Generated by Django 5.2.7 on 2025-11-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_image',
            field=models.ImageField(blank=True, null=True, upload_to='todo/completed_images'),
        ),
        migrations.AddField(
            model_name='todo',
            name='thumbnail',
            field=models.ImageField(blank=True, default='todo/no_image/NO-IMAGE.gif', null=True, upload_to='todo/thumbnails'),
        ),
    ]
