# Generated by Django 5.2.7 on 2025-11-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('free', '자유'), ('travel', '여행'), ('cat', '고양이'), ('dog', '강아지')], max_length=50, verbose_name='제목')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('content', models.TextField(verbose_name='본문')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일지')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='수정일지')),
            ],
        ),
    ]
