# Generated by Django 5.2.7 on 2025-11-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '블로그', 'verbose_name_plural': '블로그 목록'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('travel', '여행'), ('cat', '고양이'), ('dog', '강아지')], max_length=100, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
    ]
