# Generated by Django 5.2.8 on 2025-11-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_complete_alter_todo_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
