# Generated by Django 5.2.8 on 2025-11-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('poetry', '시집'), ('novel', '소설'), ('deucation', '교육'), ('self-help', '자기개발')], max_length=20)),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
                ('published_date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': '도서정보',
                'verbose_name_plural': '도서목록',
            },
        ),
    ]
